services:
  post-service:
    container_name: post-service
    build:
      context: .
      dockerfile: docker/Dockerfile
    restart: always
    env_file:
      - .env
    environment:
      DATABASE_URL: "postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}"
    depends_on:
      post_db:
        condition: service_healthy
      post_test_db:
        condition: service_healthy
    ports:
      - "${POST_SERVICE_PORT}:${POST_SERVICE_INTERNAL_PORT}"
    expose:
      - "${POST_SERVICE_INTERNAL_PORT}"
    volumes:
      - ./app:/workdir/app
      - ./migrations:/workdir/migrations
      - ./alembic.ini:/workdir/alembic.ini
      - ./tests:/workdir/tests
      - ./pytest.ini:/workdir/pytest.ini
    networks:
      - post_network
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
  post_db:
    image: postgres:17.4-alpine
    container_name: post-db
    restart: always
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      TZ: ${TIME_ZONE}
      PGTZ: ${TIME_ZONE}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    ports:
      - "5434:5432"
    volumes:
      - post_postgres_data:/var/lib/postgresql/data
    networks:
      - post_network
  post_test_db:
    image: postgres:17.4-alpine
    container_name: post-test-db
    restart: "no"
    env_file: .env
    environment:
      POSTGRES_USER: ${TEST_POSTGRES_USER}
      POSTGRES_PASSWORD: ${TEST_POSTGRES_PASSWORD}
      POSTGRES_DB: ${TEST_POSTGRES_DB}
      TZ: ${TIME_ZONE}
      PGTZ: ${TIME_ZONE}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${TEST_POSTGRES_USER} -d ${TEST_POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    ports:
      - "${TEST_POSTGRES_PORT}:5432"
    networks:
      - post_network
volumes:
  post_postgres_data:

networks:
  post_network:
    driver: bridge