services:
  auth:
    container_name: auth-service
    build:
      context: ..
      dockerfile: docker/Dockerfile
    restart: always
    env_file:
      - ../.env
    environment:
      DATABASE_URL: "postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:${POSTGRES_PORT}/${POSTGRES_DB}"
  db:
    image: postgres:17.4-alpine
    container_name: auth-db
    restart: always
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      TZ: ${TIME_ZONE}
      PGTZ: ${TIME_ZONE}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - auth_network
  test_db:
    image: postgres:17.4-alpine
    container_name: auth-test-db
    restart: "no"
    env_file: .env
    environment:
      POSTGRES_USER: ${TEST_POSTGRES_USER}
      POSTGRES_PASSWORD: ${TEST_POSTGRES_PASSWORD}
      POSTGRES_DB: ${TEST_POSTGRES_DB}
      TZ: ${TIME_ZONE}
      PGTZ: ${TIME_ZONE}
    ports:
      - "${TEST_POSTGRES_PORT}:5432"

volumes:
  postgres_data:

networks:
  auth_network:
    driver: bridge